apiVersion: v1
kind: Service
metadata:
  name: {{ include "opamp.fullname" . }}
  labels:
    {{- include "opamp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.httpPortName }}
      port: {{ .Values.service.externalHTTPPort }}
      targetPort: {{ .Values.service.internalHTTPPort }}
      protocol: TCP
      
    - name: {{ .Values.service.wsPortName }}
      port: {{ .Values.service.externalWSPort }}
      targetPort: {{ .Values.service.internalWSPort }}
      protocol: TCP
      
  selector:
    {{- include "opamp.selectorLabels" . | nindent 4 }}
