
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otaas-clusterolebinding
  labels:
    app: otaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otaas-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "otaas.serviceAccountName" . }}
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otaas-clusterrole
  labels:
    app: otaas

rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - configmaps
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for agents.greenlake.hpe.com/v1, Kind: Gloc-agent
  ##
  - apiGroups:
      - opentelemetry.io
    resources:
      - opentelemetrycollectors
      - opentelemetrycollectors/status
      - opentelemetrycollectors/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
=======
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otaas-clusterolebinding
  labels:
    app: otaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otaas-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "otaas.serviceAccountName" . }}
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otaas-clusterrole
  labels:
    app: otaas

rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - configmaps
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for agents.greenlake.hpe.com/v1, Kind: Gloc-agent
  ##
  - apiGroups:
      - opentelemetry.io
    resources:
      - opentelemetrycollectors
      - opentelemetrycollectors/status
      - opentelemetrycollectors/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---