FROM golang:1.20 as builder

WORKDIR /app

COPY test-collector-builder.yaml ./

RUN GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@latest 
RUN builder --config=test-collector-builder.yaml

# COPY otel-collector otel-collector

FROM debian:stable-slim

#RUN sed -i 's+deb http://security.debian.org/debian-security stable/updates main++g' /etc/apt/sources.list
#RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list \
# && apt-get update \
# && apt-get install -y \
#    ca-certificates \
# && rm -rf /var/lib/apt/lists/*

# Add CVE related fixes.
#RUN apt-get update \
# && apt-get install -y \
#    libssl1.1 \
#    dpkg

WORKDIR /app
COPY --from=builder /tmp/dist/otel-collector .
RUN chmod 555 /app/otel-collector

ARG USER_ID=10001
RUN groupadd -g ${USER_ID} appuser && \
    useradd -r -u ${USER_ID} -g appuser appuser

USER appuser

EXPOSE 4317 55680 55679
ENTRYPOINT ["/app/otel-collector"]
CMD ["--config", "/etc/otel/config.yaml"]

ARG TAG
ARG GIT_SHA
ARG GIT_DESCRIBE
ARG BUILD_DATE
ARG SRC_REPO
ENV TAG $TAG
ENV GIT_SHA $GIT_SHA
ENV GIT_DESCRIBE $GIT_DESCRIBE
ENV BUILD_DATE $BUILD_DATE
ENV SRC_REPO $SRC_REPO
LABEL TAG=$TAG \
  GIT_SHA=$GIT_SHA \
  GIT_DESCRIBE=$GIT_DESCRIBE \
  BUILD_DATE=$BUILD_DATE \
  SRC_REPO=$SRC_REPO

ENV IMAGE_VERSION $TAG